### ISSUE TITLE
.exe file creation error

### ISSUE THREAD

**Issue by aryan5555github** [Blank-c/Blank-Grabber#210] opened 2023-06-07 12:29 UTC
I tried to make an exe file but after it makes it it only shows an empty dist folder where is the .exe file? Before the latest update i think everything was fine

**Comment by Blank-c** [comment] 2023-06-07 12:30
Are you sure your antivirus is off?

**Comment by aryan5555github** [comment] 2023-06-07 12:31
I think it was the new update

**Comment by aryan5555github** [comment] 2023-06-08 03:05
Didn't work

**Comment by Blank-c** [comment] 2023-06-08 04:06
> Didn't work

Did you turn off the Anti VM when running in Appsonfly? Because its working fine when I tried it.

**Comment by aryan5555github** [comment] 2023-06-08 08:33
yes it didnt work i got this while opening the exe file @Blank-c 
![Screenshot 2023-06-08 003912](https://github.com/Blank-c/Blank-Grabber/assets/134721826/479635db-245c-49d2-9a76-3d33a9d0fb43)
![Screenshot 2023-05-29 045924](https://github.com/Blank-c/Blank-Grabber/assets/134721826/4d63198a-4e5d-40c6-bd19-20c9f7ccea74)

**Comment by aryan5555github** [comment] 2023-06-08 08:36
but for some reason when i made the exe file today it works! i think ur post in #209 tat to remove exit code in .bat file fixed it

**Comment by Blank-c** [comment] 2023-06-08 08:42
> yes it didnt work i got this while opening the exe file @Blank-c ![Screenshot 2023-06-08 003912](https://user-images.githubusercontent.com/134721826/244314507-479635db-245c-49d2-9a76-3d33a9d0fb43.png) ![Screenshot 2023-05-29 045924](https://user-images.githubusercontent.com/134721826/244314513-4d63198a-4e5d-40c6-bd19-20c9f7ccea74.png)

It looks like this issue is fresh. Some other people are also getting this [error](https://github.com/pyinstaller/pyinstaller/issues/7692)

Can you uninstall python 3.11 and install **3.10.(something)** . Might fix the issue

**Comment by aryan5555github** [comment] 2023-06-08 08:48
> 

idk but in my pc it works fine now

**Comment by aryan5555github** [comment] 2023-06-08 08:49
> 

for now and for ever hopefully

**Comment by aryan5555github** [comment] 2023-06-08 08:49
> > yes it didnt work i got this while opening the exe file @Blank-c ![Screenshot 2023-06-08 003912](https://user-images.githubusercontent.com/134721826/244314507-479635db-245c-49d2-9a76-3d33a9d0fb43.png) ![Screenshot 2023-05-29 045924](https://user-images.githubusercontent.com/134721826/244314513-4d63198a-4e5d-40c6-bd19-20c9f7ccea74.png)
> 
> It looks like this issue is fresh. Some other people are also getting this [error](https://github.com/pyinstaller/pyinstaller/issues/7692)
> 
> Can you uninstall python 3.11 and install **3.10.(something)** . Might fix the issue

nope i installed python 3.11 myself

**Comment by Blank-c** [comment] 2023-06-08 08:54
I did not say you did anything wrong. I just said many people (from other repositories too) got that same error just today. 

Since the issue is solved, I might close it as well.

**Closed by Blank-c** 2023-06-08 08:54 UTC

**Comment by aryan5555github** [comment] 2023-06-08 08:56
@Blank-c oh and also thanks for giving everyone such a good tool
u should also add more features

**Comment by Blank-c** [comment] 2023-06-08 15:03
Alr thanks. Suggestions are always welcome. If you wish, you can suggest some features or even contribute to the code by making PR.

**Comment by aryan5555github** [comment] 2023-07-01 09:43
@Blank-c i have ideas for many features should i make new issue or comment here

**Comment by aryan5555github** [comment] 2023-07-01 11:54
ill do it

**Comment by Blank-c** [comment] 2023-07-01 13:10
> @Blank-c i have ideas for many features should i make new issue or comment here

Feel free to make a new issue. It'd be better.
