### ISSUE TITLE
Failed to grab any chrome credentials

### ISSUE THREAD

**Issue by darknightmc80** [Blank-c/Blank-Grabber#337] opened 2023-07-28 15:43 UTC
To test my claim against it, I put it on the device and set it up. While testing, I attempted to run the payload on the PC's virtual machine, but it failed to capture the five dummy credentials that I had previously saved in Chrome.

**Comment by Blank-c** [comment] 2023-07-29 01:53
> To test my claim against it, I put it on the device and set it up. While testing, I attempted to run the payload on the PC's virtual machine, but it failed to capture the five dummy credentials that I had previously saved in Chrome.

Can you tell me:
1) The Chrome version.
2) The Windows version.
3) Does `%localappdata%\Google\Chrome\User Data` exists?
4) Is your PC a VM, and if it is then what type (Windows sandbox/VMware/Virtual Box/RDP/something else)?
5) Does [this tool](https://www.nirsoft.net/utils/web_browser_password.html) shows your passwords?

**Comment by darknightmc80** [comment] 2023-07-29 06:24
> > To test my claim against it, I put it on the device and set it up. While testing, I attempted to run the payload on the PC's virtual machine, but it failed to capture the five dummy credentials that I had previously saved in Chrome.
> 
> Can you tell me:
> 
> 1. The Chrome version.
> 2. The Windows version.
> 3. Does `%localappdata%\Google\Chrome\User Data` exists?
> 4. Is your PC a VM, and if it is then what type (Windows sandbox/VMware/Virtual Box/RDP/something else)?
> 5. Does [this tool](https://www.nirsoft.net/utils/web_browser_password.html) shows your passwords?
> 
> And if there were error logs in the archive file, can you show them?

Chrome: 115.0.5790.110
Windows: 22H2
yes it does
VMware
yep it does show em

**Comment by darknightmc80** [comment] 2023-07-29 06:27
Also side note what is the password for the Blank-Abby.rar file it generates in the dc server with the grabbed data

**Comment by Blank-c** [comment] 2023-07-29 06:29
> Also side note what is the password for the Blank-Abby.rar file it generates in the dc server with the grabbed data

Look inside config.json file along with the builder.

**Comment by Blank-c** [comment] 2023-07-29 06:49
Hey there, I am unable to reproduce the problem. Can you try to run the grabber with keeping chrome closed.

**Comment by darknightmc80** [comment] 2023-07-29 07:00
man Grammarly helps out

**Comment by Blank-c** [comment] 2023-07-29 08:24
It actually autocloses chrome. I am not sure why your chrome was still running.

**Comment by something-0001** [comment] 2023-07-30 07:33
> It actually autocloses chrome. I am not sure why your chrome was still running.

And I get why, given the credentials cannot be accessed at all while chrome is opened, I've already tried this with a different library.

**Comment by Blank-c** [comment] 2023-07-30 07:55
> > It actually autocloses chrome. I am not sure why your chrome was still running.
> 
> And I get why, given the credentials cannot be accessed at all while chrome is opened, I've already tried this with a different library.

You get them without closing chrome? May I see the code?

One thing I tried as a poc was to try to copy the chrome's `Cookies` file while it was running and Windows didn't let me do that.

**Comment by Blank-c** [comment] 2023-08-02 00:07
I have the same version of chrome but I am unable to reproduce the issue.

**Closed** 2023-08-05 07:55 UTC
Labels: bug
