### ISSUE TITLE
add all source codes to main.py instead of builder.py because i want to build myself without 30 detections

### ISSUE THREAD

**Issue by chiron853** [Blank-c/Blank-Grabber#88] opened 2022-11-28 20:08 UTC

**Comment by Blank-c** [comment] 2022-11-29 01:04
wdym?

**Comment by Blank-c** [comment] 2022-11-29 01:10
All `builder.py` does is copy files and run commands, if you want to "try" to reduce detections, here is one tip. Delete the `env` folder (if any). Delete the pyinstaller folder in Data folder, then delete these three lines from `dep.bat` in that Data folder (https://github.com/Blank-c/Blank-Grabber/blob/main/Blank%20Grabber/Data/dep.bat#L16-L18) and add a line (where you deleted those 3 lines) `pip install pyinstaller` and then run the builder. Or another way:

Build like normally till you get the exe, now go to `...\env\Scripts` folder, open cmd in that folder and then enter these commands:
```
activate
pip uninstall -y pyinstaller
pip install pyinstaller
run
```

**Comment by Blank-c** [comment] 2022-11-30 12:30
@chiron853 You there?

**Comment by chiron853** [comment] 2022-12-01 14:33
> @chiron853 You there?

yes i want to use nuitka instead of pyinstaller but how to

**Comment by Blank-c** [comment] 2022-12-01 14:48
Beats me. I never used nuitka, just heard of it.

**Comment by Blank-c** [comment] 2022-12-01 14:50
Check the pyinstaller command in `convert.bat` file and maybe try to convert it to nuitka command. Also I don't know if nuitka has `sys._MEIPASS` so it might not work as intended.

**Comment by chiron853** [comment] 2022-12-01 15:03
but you should be able to make all source in one and when you open that py file it should send info

**Comment by Blank-c** [comment] 2022-12-01 15:06
This grabber depends on more than 1 non python files and therefore is more focused on building exe.

**Comment by Blank-c** [comment] 2022-12-03 08:25
@chiron853 Anything else?

**Comment by Blank-c** [comment] 2022-12-03 16:16
Closing as seems to be completed.

**Closed by Blank-c** 2022-12-03 16:16 UTC
Labels: question
