### ISSUE TITLE
build.exe isn't opening

### ISSUE THREAD

**Issue by ANAME593** [Blank-c/Blank-Grabber#99] opened 2023-01-02 01:01 UTC
when i attempt to open build.exe a blank screen appears and closes, whats causing this

**Comment by Blank-c** [comment] 2023-01-02 01:10
Can you give more details, like
- Is the screen black? If so, can you open `cmd` in the executable's directory and then enter its name. What happen when you open it this way?
- For how long does the screen stay there?
- Are there any errors popping up?
- A video can be the best proof.

**Comment by Blank-c** [comment] 2023-01-02 02:28
Please continue it in the following thread

Duplicate of #98

**Closed by Blank-c** 2023-01-02 02:28 UTC
